{% set name = "neptune-optuna" %}
{% set package_name = "neptune_optuna" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 0a4d9442d716df14e1486714ca351513ac357f878b721a6d6fb9d275b3367877

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.7
    - neptune-client >=0.9.10
    - optuna >=2.4
    - scikit-learn >=0.24.1
    - plotly
    - poetry-dynamic-versioning

test:
  imports:
    - neptune_optuna
    - neptune_optuna.impl
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Optuna
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/hyperparameter-optimization/optuna
  dev_url: https://github.com/neptune-ai/neptune-optuna

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - Raalsky
    - twolodzko
    - AleksanderWWW
    - PatrykGala
